apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: sample-api
  newName: guilhermefaleiros/sample-api
  newTag: 96c07b1270929f3c22acc38cbdb322a786161037
